[package]
name = "parser"
version = "1.0.1"
edition = "2024"
description = "Report files parser"

[dependencies]

[[example]]
name = "binary"
path = "examples/bin_parser.rs"

[[example]]
name = "txt"
path = "examples/txt_parser.rs"

[[example]]
name = "csv"
path = "examples/csv_parser.rs"