[package]
name = "converter"
version = "1.0.2"
edition = "2024"
description = "Report files converter"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
parser = { path = "../parser" }