[package]
name = "converter"
version = "1.0.0"
edition = "2024"
description = "Report files converter tool."

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
parser = { path = "../parser" }